In [ ]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
#1 Dataframe: The frame created by data, also the structure data create from column and row, also a table
df = pd.DataFrame([12,32,43],columns=['Column 1'])
print(df)

   Column 1
0        12
1        32
2        43

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

df = pd.DataFrame(data)

In [6]:
df

   Column 1
0        12
1        32
2        43

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [2]:
Data = {
    "Name ": ["Ali","Saad", "Abu bakar","Abdulah"],
    "Age" : [12,32,23,8],
    "Salary":[1200,4321,4532,22113]
}

In [60]:
import pandas as pd
data = pd.DataFrame(Data)
print(data)

       Name   Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532
3    Abdulah    8   22113

In [4]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [11]:
#2 Basic data frame understanding

In [12]:
data.head() # By default give top 5 row

       Name   Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532
3    Abdulah    8   22113

In [13]:
data.tail() # By default give last 5 row

       Name   Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532
3    Abdulah    8   22113

In [14]:
data.shape # Tell the total rows and columns

(4, 3)

In [15]:
data.columns # It tell the all column names from the Dataframe

Index(['Name ', 'Age', 'Salary'], dtype='object')

In [16]:
#Change column name
data.rename(columns = {"Salary" : "Montholy_Salary"})

       Name   Age  Montholy_Salary
0        Ali   12             1200
1       Saad   32             4321
2  Abu bakar   23             4532
3    Abdulah    8            22113

In [17]:
data

       Name   Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532
3    Abdulah    8   22113

In [18]:
# To change the column name permanenty we have to use to methods 
# Firts methods: First method is to store the complete data frame in different variable like this
data1 = data.rename(columns={"Salary":"Monthaly_Salary"})
data1

       Name   Age  Monthaly_Salary
0        Ali   12             1200
1       Saad   32             4321
2  Abu bakar   23             4532
3    Abdulah    8            22113

In [19]:
#Secound method: Second method is to use the paramenter in the same variable with inplace  = True by default it is false but we will make is True
data.rename(columns = {"Salary" : "Monthaly_Salary"},inplace = True)
data

       Name   Age  Monthaly_Salary
0        Ali   12             1200
1       Saad   32             4321
2  Abu bakar   23             4532
3    Abdulah    8            22113

In [20]:
data.info() # it tell the information of the whole dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             4 non-null      object
 1   Age              4 non-null      int64
 2   Monthaly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [21]:
data.describe() # it describe the dataframe but it tells the statistical summary of all the numerical columns

             Age  Monthaly_Salary
count   4.000000         4.000000
mean   18.750000      8041.500000
std    10.874282      9503.892974
min     8.000000      1200.000000
25%    11.000000      3540.750000
50%    17.500000      4426.500000
75%    25.250000      8927.250000
max    32.000000     22113.000000

In [22]:
#3 Save and load data from csv

In [25]:
 # to save or export the dataframe into the system
data.to_csv("Test_data.csv")

In [26]:
# to remove the indexies from dataframe By default it is True but we will do it False
data.to_csv("Test_data.csv",index = False)

In [30]:
# To load or import the dataframe from the system 
load_data_frame = pd.read_csv("Test_data.csv")

In [31]:
load_data_frame

       Name   Age  Monthaly_Salary
0        Ali   12             1200
1       Saad   32             4321
2  Abu bakar   23             4532
3    Abdulah    8            22113
4      Ubaid   26           453112

In [32]:
#4. Rows and Columns Selections and perform operations

In [10]:
#Select column
data[['Name', 'Age']]

        Name  Age
0        Ali   12
1       Saad   32
2  Abu bakar   23
3    Abdulah    8

In [11]:
#Select Rows
# There are two methods to select rows

In [19]:
# First method: the first method works on a label base
#loc - index label based
data.loc[data.Name=="Abu bakar"]
#condition based
data.loc[(data.Name=="Abu bakar") & (data.Salary<=50000)]

        Name  Age  Salary
2  Abu bakar   23    4532

In [23]:
data.loc[0:2]
# the last value does not include in 'iloc' but include in 'loc' function

        Name  Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532

In [22]:
# secound method: The secound method works on index value base
# data.iloc[0]
#multiple index value needed
data.iloc[0:3] # [start:stop:step]
# the last value does not include in 'iloc' but include in 'loc' function

        Name  Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532

In [24]:
#05 Filter Dataframe

In [4]:
data

       Name   Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532
3    Abdulah    8   22113

In [26]:
data['Age']>18 # it tells how many value are True and False.
#if we need all the true values then we will use the bellow method

0    False
1     True
2     True
3    False
Name: Age, dtype: bool

In [29]:
data[data['Age']>=18]

        Name  Age  Salary
1       Saad   32    4321
2  Abu bakar   23    4532

In [31]:
#if we want multiple conditionn value in one line 
data[(data['Age']<18) & (data['Salary']>=1200)]

      Name  Age  Salary
0      Ali   12    1200
3  Abdulah    8   22113

In [32]:
# I want all the rows and columns of matched conditions and unmatched conditions give the null but doest not change the rows and columns

In [5]:
data.where(data['Age']>=18)

       Name    Age  Salary
0        NaN   NaN     NaN
1       Saad  32.0  4321.0
2  Abu bakar  23.0  4532.0
3        NaN   NaN     NaN

In [35]:
# NaN does not show i want somethings should show rater than NaN
# we will use the other parameter
data.where(data['Age']>=18,other = 'Not matched')

          Name          Age       Salary
0  Not matched  Not matched  Not matched
1         Saad           32         4321
2    Abu bakar           23         4532
3  Not matched  Not matched  Not matched

In [36]:
#06 Row and columns - Operations(Add,Update,Delete)

In [37]:
data

        Name  Age  Salary
0        Ali   12    1200
1       Saad   32    4321
2  Abu bakar   23    4532
3    Abdulah    8   22113

In [40]:

#Add new column and write data
data['Positions'] = ['Employee','HR','CEO','Manager']

In [41]:
data

        Name  Age  Salary Positions
0        Ali   12    1200  Employee
1       Saad   32    4321        HR
2  Abu bakar   23    4532       CEO
3    Abdulah    8   22113   Manager

In [48]:
# If we want and other column but with multiple of other like bonus the we will create like this
data['Bonus'] = data['Salary'] * 0.2
data

        Name  Age  Salary Positions   Bonus
0        Ali   12    1200  Employee   240.0
1       Saad   32    4321        HR   864.2
2  Abu bakar   23    4532       CEO   906.4
3    Abdulah    8   22113   Manager  4422.6

In [49]:
# if to add the rows data then we will use the 'loc' method
data.loc[len(data)]= ["Ahmed",20,5000,'IT',1000]
data

        Name  Age  Salary Positions   Bonus
0        Ali   12    1200  Employee   240.0
1       Saad   32    4321        HR   864.2
2  Abu bakar   23    4532       CEO   906.4
3    Abdulah    8   22113   Manager  4422.6
4      Ahmed   20    5000        IT  1000.0

In [50]:
len(data)

5

In [51]:
# update the value there are two methods

In [52]:
# Method 1 : update the value by using the index name like 0,1,2,3,4,5,6....
data.loc[0,'Salary'] = 1232113

In [53]:
data

        Name  Age   Salary Positions   Bonus
0        Ali   12  1232113  Employee   240.0
1       Saad   32     4321        HR   864.2
2  Abu bakar   23     4532       CEO   906.4
3    Abdulah    8    22113   Manager  4422.6
4      Ahmed   20     5000        IT  1000.0

In [54]:
# Method 1 : update the value by using the column name like Name == 'Abu bakar'
data.loc[data.Name=='Abu bakar','Salary'] = 120000
data

        Name  Age   Salary Positions   Bonus
0        Ali   12  1232113  Employee   240.0
1       Saad   32     4321        HR   864.2
2  Abu bakar   23   120000       CEO   906.4
3    Abdulah    8    22113   Manager  4422.6
4      Ahmed   20     5000        IT  1000.0

In [55]:
#Delete value - row and column

In [67]:
data.drop(data[data.Name=='Ahmed'].index,inplace=True) #delete row , axis = 0
data

        Name  Age   Salary Positions   Bonus
0        Ali   12  1232113  Employee   240.0
1       Saad   32     4321        HR   864.2
2  Abu bakar   23   120000       CEO   906.4
3    Abdulah    8    22113   Manager  4422.6

In [ ]:
#Secound method to delete row with index lable
data.drop(1.,axis=0,inplace=True) #delete row , axis = 0
data

In [73]:
data.drop('Bonus',axis=1,inplace=True) #delete columns , axis=1
data

        Name  Age   Salary Positions
0        Ali   12  1232113  Employee
1       Saad   32     4321        HR
2  Abu bakar   23   120000       CEO
3    Abdulah    8    22113   Manager

In [74]:
#for multiple delete columns

In [75]:
# data.drop(['Name','Age','Salary'],axis=1)

In [79]:
# Sort value -  in ascending and descending 
data.sort_values('Salary') #in ascending

        Name  Age   Salary Positions
1       Saad   32     4321        HR
3    Abdulah    8    22113   Manager
2  Abu bakar   23   120000       CEO
0        Ali   12  1232113  Employee

In [81]:
data.sort_values('Salary',ascending= False) #in dscending

        Name  Age   Salary Positions
0        Ali   12  1232113  Employee
2  Abu bakar   23   120000       CEO
3    Abdulah    8    22113   Manager
1       Saad   32     4321        HR

In [82]:
#07 Working with date time value or datatype

In [66]:
data['Date of Joinnig'] = ['2026-1-21','2026-1-22','2026-2-3','2026-3-1']

In [67]:
data

       Name   Age  Salary Date of Joinnig
0        Ali   12    1200       2026-1-21
1       Saad   32    4321       2026-1-22
2  Abu bakar   23    4532        2026-2-3
3    Abdulah    8   22113        2026-3-1

In [68]:
data['Date of Joinnig'].dtype

dtype('O')

In [69]:
data.rename(columns={'Date of Joinnig':'DOJ'},inplace=True)
data

       Name   Age  Salary        DOJ
0        Ali   12    1200  2026-1-21
1       Saad   32    4321  2026-1-22
2  Abu bakar   23    4532   2026-2-3
3    Abdulah    8   22113   2026-3-1

In [70]:
data['DOJ'] = pd.to_datetime(data['DOJ'])# Convert date Object into date and time

In [71]:
data['DOJ'].dtype

dtype('<M8[ns]')

In [72]:
#formate the date
data['DOJ'] = pd.to_datetime(data['DOJ'],format='%d-%m-%Y')

In [26]:
data

       Name   Age  Salary        DOJ
0        Ali   12    1200 2026-01-21
1       Saad   32    4321 2026-01-22
2  Abu bakar   23    4532 2026-02-03
3    Abdulah    8   22113 2026-03-01

In [29]:
data['DOJ'].dt.year # to find the year from DOJ
data['DOJ'].dt.month # to find the month from DOJ
data['DOJ'].dt.month_name() # to find the month name from DOJ
data['DOJ'].dt.day # to find the day from DOJ
data['DOJ'].dt.day_name() # to find the day name from DOJ

0    Wednesday
1     Thursday
2      Tuesday
3       Sunday
Name: DOJ, dtype: object

In [73]:
data['Month'] = data['DOJ'].dt.month_name() # joing months

In [74]:
data

       Name   Age  Salary        DOJ     Month
0        Ali   12    1200 2026-01-21   January
1       Saad   32    4321 2026-01-22   January
2  Abu bakar   23    4532 2026-02-03  February
3    Abdulah    8   22113 2026-03-01     March

In [75]:
data['Probation time end data ']= data['DOJ'] + pd.Timedelta(days=90) #use to add the extra days in DOJ

In [76]:
data

       Name   Age  Salary        DOJ     Month Probation time end data
0        Ali   12    1200 2026-01-21   January               2026-04-21
1       Saad   32    4321 2026-01-22   January               2026-04-22
2  Abu bakar   23    4532 2026-02-03  February               2026-05-04
3    Abdulah    8   22113 2026-03-01     March               2026-05-30

In [77]:
#08 Handling missing values

In [90]:
import numpy as np

In [81]:
data.rename(columns= {'Name ':'Name'},inplace = True)

In [91]:
data.loc[data.Name=='Ali','Salary'] = np.nan # for make the value null in any row

In [92]:
data

        Name  Age   Salary        DOJ     Month Probation time end data
0        Ali   12      NaN 2026-01-21   January               2026-04-21
1       Saad   32   4321.0 2026-01-22   January               2026-04-22
2  Abu bakar   23   4532.0 2026-02-03  February               2026-05-04
3    Abdulah    8  22113.0 2026-03-01     March               2026-05-30

In [93]:
data.isnull() # it tells the null value 'True' at any where in Dataframe

    Name    Age  Salary    DOJ  Month  Probation time end data
0  False  False    True  False  False                     False
1  False  False   False  False  False                     False
2  False  False   False  False  False                     False
3  False  False   False  False  False                     False

In [94]:
data.isnull().sum() # it gives the totl nul vaues

Name                        0
Age                         0
Salary                      1
DOJ                         0
Month                       0
Probation time end data     0
dtype: int64

In [101]:
data.fillna(321121) # it add the value in null sector

        Name  Age    Salary        DOJ     Month Probation time end data
0        Ali   12  321121.0 2026-01-21   January               2026-04-21
1       Saad   32    4321.0 2026-01-22   January               2026-04-22
2  Abu bakar   23    4532.0 2026-02-03  February               2026-05-04
3    Abdulah    8   22113.0 2026-03-01     March               2026-05-30

In [102]:
data

        Name  Age   Salary        DOJ     Month Probation time end data
0        Ali   12      NaN 2026-01-21   January               2026-04-21
1       Saad   32   4321.0 2026-01-22   January               2026-04-22
2  Abu bakar   23   4532.0 2026-02-03  February               2026-05-04
3    Abdulah    8  22113.0 2026-03-01     March               2026-05-30

In [103]:
#09 Aggregasion and group By

In [106]:
# To find total value of any thing in dataframe
data['Name'].value_counts()

Name
Ali          1
Saad         1
Abu bakar    1
Abdulah      1
Name: count, dtype: int64

In [109]:
# To find total value of any specific data in dataframe
data[data['Month']=='January'].value_counts()

Name  Age  Salary  DOJ         Month    Probation time end data
Saad  32   4321.0  2026-01-22  January  2026-04-22                  1
Name: count, dtype: int64

In [111]:
#group by it tell total sum of any integer column in data frame

In [113]:
data.groupby('Month')['Salary'].sum() # Agrregation based on group by

Month
February     4532.0
January      4321.0
March       22113.0
Name: Salary, dtype: float64

In [114]:
data.groupby('Month').agg({'Salary':'mean','Name':'count'})

           Salary  Name
Month
February   4532.0     1
January    4321.0     2
March     22113.0     1